### ISSUE TITLE
Exception has occurred: ValueError Coordinates out side of printer bed 

### ISSUE THREAD

**Issue by malekinho8** [BuysDB/plotting3dprinter#3]
Code to reproduce error:

```
from plotting3dprinter.svg_to_gcode import svg_to_gcode

def test_svg_to_gcode():
    svg_path = "examples\\escher_waterfall\\waterfall_trace.svg"
    gcode_path = 'gcode\\test.gcode'
    svg_to_gcode(svg_path, gcode_path, speed=4000, x_offset=0, y_offset=0)

test_svg_to_gcode()
```

I also checked using the default values for `x_offset` and `y_offset`, and I still received the same error. Am I doing something wrong here?

**Comment by BuysDB** [comment]
Hi, thanks for opening an issue. I have changed the error message to be more descriptive.  The SVG is larger than would fit on the bed, and it needs to be scaled in order to make it fit.
You just need to pass  the `longest_edge` parameter to for example `longest_edge=200`

`svgto3dprintplot waterfall_trace.svg example_outline.gcode --stroke -longest_edge 200`

**Comment by malekinho8** [comment]
> Hi, thanks for opening an issue. I have changed the error message to be more descriptive. The SVG is larger than would fit on the bed, and it needs to be scaled in order to make it fit. You just need to pass the `longest_edge` parameter to for example `longest_edge=200`
> 
> `svgto3dprintplot waterfall_trace.svg example_outline.gcode --stroke -longest_edge 200`

That makes much more sense now thanks for the quick reply!
